Package Requirements

In [ ]:
!pip install ddgs
!pip install httpx
!pip install newspaper3k
!pip install lxml_html_clean
!pip install spacy
!python -m spacy download en_core_web_sm

Requirement already satisfied: ddgs in c:\users\faman\appdata\roaming\python\python313\site-packages (9.10.0)
Requirement already satisfied: click>=8.1.8 in c:\users\faman\.conda\envs\qc\lib\site-packages (from ddgs) (8.3.1)
Requirement already satisfied: primp>=0.15.0 in c:\users\faman\appdata\roaming\python\python313\site-packages (from ddgs) (1.0.0)
Requirement already satisfied: lxml>=4.9.4 in c:\users\faman\.conda\envs\qc\lib\site-packages (from ddgs) (6.0.2)
Requirement already satisfied: httpx>=0.28.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx[brotli,http2,socks]>=0.28.1->ddgs) (0.28.1)
Requirement already satisfied: fake-useragent>=2.2.0 in c:\users\faman\appdata\roaming\python\python313\site-packages (from ddgs) (2.2.0)
Requirement already satisfied: colorama in c:\users\faman\.conda\envs\qc\lib\site-packages (from click>=8.1.8->ddgs) (0.4.6)
Requirement already satisfied: anyio in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx>=0.28.1->httpx[brotli,http2,socks]>=0.28.1->ddgs) (4.12.1)
Requirement already satisfied: certifi in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx>=0.28.1->httpx[brotli,http2,socks]>=0.28.1->ddgs) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx>=0.28.1->httpx[brotli,http2,socks]>=0.28.1->ddgs) (1.0.9)
Requirement already satisfied: idna in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx>=0.28.1->httpx[brotli,http2,socks]>=0.28.1->ddgs) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpcore==1.*->httpx>=0.28.1->httpx[brotli,http2,socks]>=0.28.1->ddgs) (0.16.0)
Requirement already satisfied: brotli in c:\users\faman\appdata\roaming\python\python313\site-packages (from httpx[brotli,http2,socks]>=0.28.1->ddgs) (1.2.0)
Requirement already satisfied: h2<5,>=3 in c:\users\faman\appdata\roaming\python\python313\site-packages (from httpx[brotli,http2,socks]>=0.28.1->ddgs) (4.3.0)
Requirement already satisfied: socksio==1.* in c:\users\faman\appdata\roaming\python\python313\site-packages (from httpx[brotli,http2,socks]>=0.28.1->ddgs) (1.0.0)
Requirement already satisfied: hyperframe<7,>=6.1 in c:\users\faman\appdata\roaming\python\python313\site-packages (from h2<5,>=3->httpx[brotli,http2,socks]>=0.28.1->ddgs) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in c:\users\faman\appdata\roaming\python\python313\site-packages (from h2<5,>=3->httpx[brotli,http2,socks]>=0.28.1->ddgs) (4.1.0)
Requirement already satisfied: httpx in c:\users\faman\.conda\envs\qc\lib\site-packages (0.28.1)
Requirement already satisfied: anyio in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx) (4.12.1)
Requirement already satisfied: certifi in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx) (1.0.9)
Requirement already satisfied: idna in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpx) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\faman\.conda\envs\qc\lib\site-packages (from httpcore==1.*->httpx) (0.16.0)
Requirement already satisfied: newspaper3k in c:\users\faman\appdata\roaming\python\python313\site-packages (0.2.8)
Requirement already satisfied: beautifulsoup4>=4.4.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (4.14.3)
Requirement already satisfied: Pillow>=3.3.0 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (12.0.0)
Requirement already satisfied: PyYAML>=3.11 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (6.0.3)
Requirement already satisfied: cssselect>=0.9.2 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (1.4.0)
Requirement already satisfied: lxml>=3.6.0 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (6.0.2)
Requirement already satisfied: nltk>=3.2.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (3.9.2)
Requirement already satisfied: requests>=2.10.0 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (2.32.5)
Requirement already satisfied: feedparser>=5.2.1 in c:\users\faman\appdata\roaming\python\python313\site-packages (from newspaper3k) (6.0.12)
Requirement already satisfied: tldextract>=2.0.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (5.3.1)
Requirement already satisfied: feedfinder2>=0.0.4 in c:\users\faman\appdata\roaming\python\python313\site-packages (from newspaper3k) (0.0.4)
Requirement already satisfied: jieba3k>=0.35.1 in c:\users\faman\appdata\roaming\python\python313\site-packages (from newspaper3k) (0.35.1)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\faman\.conda\envs\qc\lib\site-packages (from newspaper3k) (2.9.0.post0)
Requirement already satisfied: tinysegmenter==0.3 in c:\users\faman\appdata\roaming\python\python313\site-packages (from newspaper3k) (0.3)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\faman\.conda\envs\qc\lib\site-packages (from beautifulsoup4>=4.4.1->newspaper3k) (4.15.0)
Requirement already satisfied: six in c:\users\faman\.conda\envs\qc\lib\site-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)
Requirement already satisfied: sgmllib3k in c:\users\faman\appdata\roaming\python\python313\site-packages (from feedparser>=5.2.1->newspaper3k) (1.0.0)
Requirement already satisfied: click in c:\users\faman\.conda\envs\qc\lib\site-packages (from nltk>=3.2.1->newspaper3k) (8.3.1)
Requirement already satisfied: joblib in c:\users\faman\.conda\envs\qc\lib\site-packages (from nltk>=3.2.1->newspaper3k) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\faman\.conda\envs\qc\lib\site-packages (from nltk>=3.2.1->newspaper3k) (2025.11.3)
Requirement already satisfied: tqdm in c:\users\faman\.conda\envs\qc\lib\site-packages (from nltk>=3.2.1->newspaper3k) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\faman\.conda\envs\qc\lib\site-packages (from requests>=2.10.0->newspaper3k) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\faman\.conda\envs\qc\lib\site-packages (from requests>=2.10.0->newspaper3k) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\faman\.conda\envs\qc\lib\site-packages (from requests>=2.10.0->newspaper3k) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\faman\.conda\envs\qc\lib\site-packages (from requests>=2.10.0->newspaper3k) (2025.11.12)
Requirement already satisfied: requests-file>=1.4 in c:\users\faman\.conda\envs\qc\lib\site-packages (from tldextract>=2.0.1->newspaper3k) (3.0.1)
Requirement already satisfied: filelock>=3.0.8 in c:\users\faman\.conda\envs\qc\lib\site-packages (from tldextract>=2.0.1->newspaper3k) (3.24.3)
Requirement already satisfied: colorama in c:\users\faman\.conda\envs\qc\lib\site-packages (from click->nltk>=3.2.1->newspaper3k) (0.4.6)
Requirement already satisfied: lxml_html_clean in c:\users\faman\appdata\roaming\python\python313\site-packages (0.4.3)
Requirement already satisfied: lxml in c:\users\faman\.conda\envs\qc\lib\site-packages (from lxml_html_clean) (6.0.2)

Retrieve articles using duckduckgo search text method - no filter applied yet

In [2]:
import pandas as pd
from ddgs import DDGS
import newspaper
from newspaper import Article

In [3]:
results = DDGS().text(query="galgotias impact ai summit", region="in-en",safesearch= "off", timelimit="7d", max_results=30)
df=pd.DataFrame(results)
df

Impersonate 'chrome_127' does not exist, using 'random'

                                                title  ...                                               body
0             India AI Impact Summit 2026 - Wikipedia  ...  2024, the AI Action Summit in Paris in 2025, a...
1   Galgotias : Who’s really to blame? And what In...  ...  At the AI summit , I found that much of the mo...
2   Galgotias under fire for displaying Chinese ro...  ...  Galgotias University has addressed online crit...
3   Galgotias University leaves AI Summit with rob...  ...  Trinamool Congress MP Saket Gokhale questioned...
4   ‘She was not authorised to …’: Galgotias Unive...  ...  In a detailed statement issued after being ask...
5   Moving past Galgotias row, desi tech emerges r...  ...  Even as the Galgotias robot dog controversy do...
6   ‘We Do Not Want Any Controversy’: IT Ministry ...  ...  The controversy erupted at the AI Impact Summi...
7   Galgotias University Faces Viral Mockery at AI...  ...  Galgotias University faced widespread ridicule...
8   Galgotias University Pavilion Emerges as a Key...  ...  Galgotias University Pavilion at AI Impact Sum...
9   Galgotias University responds after being accu...  ...  The Greater Noida university had come under fi...
10  Galgotias University accused of showcasing... ...  ...  “So Galgotia university purchased a commercial...
11  Galgotias University ने देसी बताकर पेश कर दिया...  ...  India AI Impact Summit 2026 में Galgotias Univ...
12  Video Summary - China Mocks India over Al Summ...  ...  AI Impact Summit — “Orion” robot controversy. ...
13  Galgotias University booted from India AI Impa...  ...  A private Indian university has been booted fr...
14  Galgotias University asked to vacate AI Impact...  ...  Galgotias University faced removal from the AI...
15  Exit, blame, warning: Galgotias' Chinese robod...  ...  Galgotias University found itself in the eye o...
16  Galgotias University AI Robot Dog Controversy ...  ...  A row has erupted at the India AI Impact Summi...
17  Galgotias University staff leave AI Impact Exp...  ...  Galgotias University confirms its Robodog at A...
18  Galgotias University asked to vacate AI Summit...  ...  Organisers of the AI Impact Summit ousted priv...
19  After robot dog row at AI Summit, Galgotias ap...  ...  After Galgotias University was asked to vacate...
20  Galgotias University officials leave AI Impact...  ...  This came after reports suggested that Galgoti...
21  Galgotias University vacate stall at India AI ...  ...  Galgotias University staff and officials vacat...
22  AI Summit: Galgotias University's booth was bi...  ...  22 hours ago · Galgotias University was allott...
23  Galgotias Chaos at AI Summit Reveals Deeper Ro...  ...  2 days ago · The Galgotias imbroglio managed t...
24  Galgotias University after being told to pack ...  ...  3 days ago · The private institution was asked...
25  'We are sorry': Galgotias says Neha Singh not ...  ...  1 day ago · Galgotias University says professo...
26  Fiasco at India AI Expo: Galgotias University ...  ...  23 hours ago · The Galgotias University incide...
27  Robodog row: Galgotias out of AI Summit - Hind...  ...  3 days ago · Galgotias University faced backla...
28  AI Summit: After Galgotias University, Wipro F...  ...  3 days ago · However, on Wednesday (February 1...
29  " AI Impact Summit Reduced To School-Level Sci...  ...  About Press Copyright Contact us Creators Adve...

[30 rows x 3 columns]

In [4]:
for url in df['href']:
    try:
        article = Article(url)
        article.download()
        article.parse()
        df.loc[df['href'] == url, 'text'] = article.text
    except Exception as e:
        print(f"Error processing URL {url}: {e}")
df

Error processing URL https://www.hindustantimes.com/trending/galgotias-university-responds-after-being-accused-of-passing-off-chinese-robot-dog-as-its-own-at-ai-summit-101771379191282.html: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.hindustantimes.com/trending/galgotias-university-responds-after-being-accused-of-passing-off-chinese-robot-dog-as-its-own-at-ai-summit-101771379191282.html on URL https://www.hindustantimes.com/trending/galgotias-university-responds-after-being-accused-of-passing-off-chinese-robot-dog-as-its-own-at-ai-summit-101771379191282.html
Error processing URL https://www.hindustantimes.com/india-news/exit-blame-apology-and-centres-warning-galgotias-universitys-chinese-robodog-row-at-ai-summit-2026-key-points-101771466897249.html: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.hindustantimes.com/india-news/exit-blame-apology-and-centres-warning-galgotias-universitys-chinese-robodog-row-at-ai-summit-2026-key-points-101771466897249.html on URL https://www.hindustantimes.com/india-news/exit-blame-apology-and-centres-warning-galgotias-universitys-chinese-robodog-row-at-ai-summit-2026-key-points-101771466897249.html
Error processing URL https://indianexpress.com/article/delhi/robot-dog-ai-india-expo-summit-galgotias-university-public-10538752/: Article `download()` failed with HTTPSConnectionPool(host='indianexpress.com', port=443): Read timed out. (read timeout=7) on URL https://indianexpress.com/article/delhi/robot-dog-ai-india-expo-summit-galgotias-university-public-10538752/
Error processing URL https://www.thequint.com/opinion/ai-summit-india-galgotias-chinese-robot-dog-innovation-scandal-education: Article `download()` failed with HTTPSConnectionPool(host='www.thequint.com', port=443): Read timed out. on URL https://www.thequint.com/opinion/ai-summit-india-galgotias-chinese-robot-dog-innovation-scandal-education
Error processing URL https://www.hindustantimes.com/india-news/robodog-row-galgotias-out-of-ai-summit-101771442376956.html: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.hindustantimes.com/india-news/robodog-row-galgotias-out-of-ai-summit-101771442376956.html on URL https://www.hindustantimes.com/india-news/robodog-row-galgotias-out-of-ai-summit-101771442376956.html

                                                title  ...                                               text
0             India AI Impact Summit 2026 - Wikipedia  ...  2026 conference in Delhi, India\n\nThe AI Impa...
1   Galgotias : Who’s really to blame? And what In...  ...  My six can be your nine.\n\nAs Professor Neha ...
2   Galgotias under fire for displaying Chinese ro...  ...  Galgotias University, which is facing an onlin...
3   Galgotias University leaves AI Summit with rob...  ...  New Delhi | The internet never forgets and the...
4   ‘She was not authorised to …’: Galgotias Unive...  ...  Galgotias University apologizes after a contro...
5   Moving past Galgotias row, desi tech emerges r...  ...  Advertisement\n\nMandeep Singh, Asistant Dean ...
6   ‘We Do Not Want Any Controversy’: IT Ministry ...  ...  Show Quick Read Key points generated by AI, ve...
7   Galgotias University Faces Viral Mockery at AI...  ...  Galgotias University faced widespread ridicule...
8   Galgotias University Pavilion Emerges as a Key...  ...  Galgotias University witnessed strong engageme...
9   Galgotias University responds after being accu...  ...                                                NaN
10  Galgotias University accused of showcasing... ...  ...  A social media post alleging that Galgotias Un...
11  Galgotias University ने देसी बताकर पेश कर दिया...  ...  ETV Bharat / technology\n\nGalgotias Universit...
12  Video Summary - China Mocks India over Al Summ...  ...  Summary of "China Mocks India over Al Summit B...
13  Galgotias University booted from India AI Impa...  ...  Add AP News as your preferred source to see mo...
14  Galgotias University asked to vacate AI Impact...  ...  It seems like you're already an ETPrime member...
15  Exit, blame, warning: Galgotias' Chinese robod...  ...                                                NaN
16  Galgotias University AI Robot Dog Controversy ...  ...  Professor Neha Singh, who appeared in the orig...
17  Galgotias University staff leave AI Impact Exp...  ...  \n\n#WATCH | Delhi | Galgotias University staf...
18  Galgotias University asked to vacate AI Summit...  ...  Organisers of the AI Impact Summit ousted priv...
19  After robot dog row at AI Summit, Galgotias ap...  ...                                                NaN
20  Galgotias University officials leave AI Impact...  ...  Galgotiyas University staff and officials were...
21  Galgotias University vacate stall at India AI ...  ...  India's Galgotias University courted a major c...
22  AI Summit: Galgotias University's booth was bi...  ...  After robodog fiasco, Galgotias University's g...
23  Galgotias Chaos at AI Summit Reveals Deeper Ro...  ...                                                NaN
24  Galgotias University after being told to pack ...  ...  Govt sources said the robotic dog, presented b...
25  'We are sorry': Galgotias says Neha Singh not ...  ...  Registrar Nitin Kumar Gaur says university has...
26  Fiasco at India AI Expo: Galgotias University ...  ...  The Galgotias University incident has put the ...
27  Robodog row: Galgotias out of AI Summit - Hind...  ...                                                NaN
28  AI Summit: After Galgotias University, Wipro F...  ...  Wipro has, however, defended it saying its foc...
29  " AI Impact Summit Reduced To School-Level Sci...  ...

[30 rows x 4 columns]

Data preparation

In [5]:
df.dropna(inplace=True)
df

                                                title  ...                                               text
0             India AI Impact Summit 2026 - Wikipedia  ...  2026 conference in Delhi, India\n\nThe AI Impa...
1   Galgotias : Who’s really to blame? And what In...  ...  My six can be your nine.\n\nAs Professor Neha ...
2   Galgotias under fire for displaying Chinese ro...  ...  Galgotias University, which is facing an onlin...
3   Galgotias University leaves AI Summit with rob...  ...  New Delhi | The internet never forgets and the...
4   ‘She was not authorised to …’: Galgotias Unive...  ...  Galgotias University apologizes after a contro...
5   Moving past Galgotias row, desi tech emerges r...  ...  Advertisement\n\nMandeep Singh, Asistant Dean ...
6   ‘We Do Not Want Any Controversy’: IT Ministry ...  ...  Show Quick Read Key points generated by AI, ve...
7   Galgotias University Faces Viral Mockery at AI...  ...  Galgotias University faced widespread ridicule...
8   Galgotias University Pavilion Emerges as a Key...  ...  Galgotias University witnessed strong engageme...
10  Galgotias University accused of showcasing... ...  ...  A social media post alleging that Galgotias Un...
11  Galgotias University ने देसी बताकर पेश कर दिया...  ...  ETV Bharat / technology\n\nGalgotias Universit...
12  Video Summary - China Mocks India over Al Summ...  ...  Summary of "China Mocks India over Al Summit B...
13  Galgotias University booted from India AI Impa...  ...  Add AP News as your preferred source to see mo...
14  Galgotias University asked to vacate AI Impact...  ...  It seems like you're already an ETPrime member...
16  Galgotias University AI Robot Dog Controversy ...  ...  Professor Neha Singh, who appeared in the orig...
17  Galgotias University staff leave AI Impact Exp...  ...  \n\n#WATCH | Delhi | Galgotias University staf...
18  Galgotias University asked to vacate AI Summit...  ...  Organisers of the AI Impact Summit ousted priv...
20  Galgotias University officials leave AI Impact...  ...  Galgotiyas University staff and officials were...
21  Galgotias University vacate stall at India AI ...  ...  India's Galgotias University courted a major c...
22  AI Summit: Galgotias University's booth was bi...  ...  After robodog fiasco, Galgotias University's g...
24  Galgotias University after being told to pack ...  ...  Govt sources said the robotic dog, presented b...
25  'We are sorry': Galgotias says Neha Singh not ...  ...  Registrar Nitin Kumar Gaur says university has...
26  Fiasco at India AI Expo: Galgotias University ...  ...  The Galgotias University incident has put the ...
28  AI Summit: After Galgotias University, Wipro F...  ...  Wipro has, however, defended it saying its foc...
29  " AI Impact Summit Reduced To School-Level Sci...  ...

[25 rows x 4 columns]

need to automate the next cell, don't know how yet

In [6]:
df.drop([13,14,17,29],axis=0, inplace=True)
df.reset_index(drop=True, inplace=True)
df

                                                title  ...                                               text
0             India AI Impact Summit 2026 - Wikipedia  ...  2026 conference in Delhi, India\n\nThe AI Impa...
1   Galgotias : Who’s really to blame? And what In...  ...  My six can be your nine.\n\nAs Professor Neha ...
2   Galgotias under fire for displaying Chinese ro...  ...  Galgotias University, which is facing an onlin...
3   Galgotias University leaves AI Summit with rob...  ...  New Delhi | The internet never forgets and the...
4   ‘She was not authorised to …’: Galgotias Unive...  ...  Galgotias University apologizes after a contro...
5   Moving past Galgotias row, desi tech emerges r...  ...  Advertisement\n\nMandeep Singh, Asistant Dean ...
6   ‘We Do Not Want Any Controversy’: IT Ministry ...  ...  Show Quick Read Key points generated by AI, ve...
7   Galgotias University Faces Viral Mockery at AI...  ...  Galgotias University faced widespread ridicule...
8   Galgotias University Pavilion Emerges as a Key...  ...  Galgotias University witnessed strong engageme...
9   Galgotias University accused of showcasing... ...  ...  A social media post alleging that Galgotias Un...
10  Galgotias University ने देसी बताकर पेश कर दिया...  ...  ETV Bharat / technology\n\nGalgotias Universit...
11  Video Summary - China Mocks India over Al Summ...  ...  Summary of "China Mocks India over Al Summit B...
12  Galgotias University AI Robot Dog Controversy ...  ...  Professor Neha Singh, who appeared in the orig...
13  Galgotias University asked to vacate AI Summit...  ...  Organisers of the AI Impact Summit ousted priv...
14  Galgotias University officials leave AI Impact...  ...  Galgotiyas University staff and officials were...
15  Galgotias University vacate stall at India AI ...  ...  India's Galgotias University courted a major c...
16  AI Summit: Galgotias University's booth was bi...  ...  After robodog fiasco, Galgotias University's g...
17  Galgotias University after being told to pack ...  ...  Govt sources said the robotic dog, presented b...
18  'We are sorry': Galgotias says Neha Singh not ...  ...  Registrar Nitin Kumar Gaur says university has...
19  Fiasco at India AI Expo: Galgotias University ...  ...  The Galgotias University incident has put the ...
20  AI Summit: After Galgotias University, Wipro F...  ...  Wipro has, however, defended it saying its foc...

[21 rows x 4 columns]

In [7]:
df.to_csv("C:/Users/faman/Downloads/ddgs_results_cleaned.csv", index=False)

pre-processing data into tokenized sentences

In [10]:
all_text = ' '.join(df['text'])
all_text = all_text.lower()
all_text

'2026 conference in delhi, india\n\nthe ai impact summit, formally the india ai impact summit 2026, is an international summit on artificial intelligence held at bharat mandapam, new delhi, india, from 16 to 21 february 2026.[1][2] it is the fourth in a series of global ai summits following the bletchley park ai safety summit in 2023, the ai seoul summit in 2024, and the ai action summit in paris in 2025.[3] organised under the indiaai mission by the ministry of electronics and information technology, it is the first summit in the series to be hosted by a global south nation.\n\nthe summit was inaugurated by prime minister narendra modi on 19 february 2026.[4] the opening ceremony was also addressed by french president emmanuel macron and united nations secretary-general antónio guterres.[5]\n\nthe event faced criticism for not being properly organised, misrepresentation of chinese products as indian products, and the use of event for pr by the ruling government.\n\nbackground [ edit ]\n\nthe ai impact summit is an international summit on artificial intelligence (ai) scheduled to be held in new delhi from 16 to 20 february 2026.[6][7] it follows the ai action summit in paris in february 2025, the 2024 ai seoul summit in 2024 and the bletchley park ai safety summit in 2023.\n\naccording to crowell & moring, the changing summit titles seem to reflect a broader shift in focus away from ai safety and governance toward practical impact, implementation, and measurable outcomes.[8]\n\nahead of the summit, an international panel of experts published the second international ai safety report.[9]\n\nthe summit was structured around three foundational pillars, termed "sutras": people, planet, and progress.[1] seven thematic working groups were established to deliver outcomes across these pillars, covering ai for economic growth and social good; democratising ai resources; inclusion for social empowerment; safe and trusted ai; human capital; science; and resilience, innovation, and efficiency.[2]\n\nprogramme [ edit ]\n\nthe summit ran over five days, later extended to six following overwhelming public response.[10] originally scheduled to conclude on 20 february, the event was extended to 21 february with expanded evening hours for the exhibition.[11]\n\nindia ai impact expo [ edit ]\n\nthe india ai impact expo, inaugurated by prime minister modi on 16 february, featured over 300 exhibitors from 30 countries across more than 10 thematic pavilions.[12] pavilions were organised across thematic zones aligned with the summit\'s three pillars, showcasing ai applications in healthcare, agriculture, education, and sustainable industry.[2]\n\nleaders\' plenary and ceo roundtable [ edit ]\n\nthe leaders\' plenary on 19 february brought together heads of state, ministers, and representatives from multilateral institutions to outline national and global priorities on ai governance, infrastructure, and international cooperation.[4] a ceo roundtable, held the same evening, convened senior executives from global technology and industry firms with government leaders to discuss investment, research collaboration, and deployment of ai systems.[4]\n\nresearch symposium [ edit ]\n\na research symposium on ai and its impact was held on 18 february, with the iiit hyderabad as knowledge partner. discussions covered sovereign ai infrastructure, global adoption challenges, research breakthroughs, and policy priorities.[13]\n\nparticipants [ edit ]\n\nthe summit drew delegations from over 100 countries, including more than 20 heads of state and 60 ministers. notable attendees from the technology industry included sundar pichai (google), sam altman (openai), dario amodei (anthropic), demis hassabis (google deepmind), and mukesh ambani (reliance industries).[5] representatives from multilateral institutions included sangbu kim of the world bank.[14]\n\nannouncements and outcomes [ edit ]\n\nindian ai models [ edit ]\n\nseveral indian ai models and products were unveiled during the summit. sarvam ai, an indian ai laboratory, launched a new generation of large language models, including 30-billion and 105-billion parameter models using a mixture of experts architecture, as well as text-to-speech, speech-to-text, and vision models.[15] sarvam also introduced the kaze smartglasses, described as the company\'s first hardware product, which prime minister modi tested at the expo.[16]\n\nthe government-backed bharatgen param2 model, a 17-billion parameter model supporting 22 indian languages with multimodal capabilities, was also launched at the summit.[17]\n\ninfrastructure commitments [ edit ]\n\nunion minister ashwini vaishnaw outlined india\'s "whole-of-nation" ai strategy, describing plans to build a "frugal, sovereign and scalable" ai ecosystem.[18] the government announced plans to add more than 20,000 gpus to india\'s existing base of 38,000 under the indiaai compute portal.[17]\n\nmicrosoft announced at the summit that it was on track to invest us$50 billion by the end of the decade to bring ai to lower-income countries.[19]\n\nguinness world record [ edit ]\n\nduring the summit, india set a guinness world record for the most pledges received for an ai responsibility campaign in 24 hours, with 250,946 valid pledges collected between 16 and 17 february 2026.[20] the campaign, conducted in partnership with intel india as part of the indiaai mission, exceeded its initial target of 5,000 pledges.[21]\n\ncontroversies [ edit ]\n\ngalgotias university incident [ edit ]\n\non 18 february, galgotias university faced widespread criticism after a representative presented a robot dog at the university\'s exhibition pavilion as an indigenous development. social media users identified the robot as the unitree go2, a commercially available product manufactured by chinese company unitree robotics.[22][23] it secretary s. krishnan stated that the government did not want exhibitors to showcase items that were not their own, and the university was directed to vacate its stall.[24] galgotias university issued an apology, stating that the representative had been "ill-informed" and was not authorised to speak to the press.[25]\n\nthe incident drew political reactions, with the indian national congress using it to criticise the government.[22] the controversy was amplified after union it minister ashwini vaishnaw had earlier shared a video clip of the robot on social media, which was subsequently deleted.[23]\n\norganisational issues [ edit ]\n\non day 1 of the summit, dhananjay yadav, a bengaluru-based entrepreneur had alleged that his product was stolen in the summit. he called it as a pain for the people in an x post. he further wrote, "think about this: we paid for flights, accommodation, logistics and even the booth. only to see our wearables disappear inside a high-security zone".[26] later, the stolen devices were recovered by the delhi police.[27]\n\nbloomberg reported that delegates were left stranded without food or water during a security lockdown ahead of the prime minister\'s visit on 19 february.[28] the summit venue was closed to the public on 19 february for the prime minister\'s visit, leading to criticism from attendees who had registered for that day.[29]\n\nreception and analysis [ edit ]\n\nbloomberg news reported that prime minister modi used the summit to assert india\'s global ai ambitions following a challenging year in foreign policy.[30]\n\ntechpolicy.press published several critical analyses of the summit. one article argued that the summit\'s structure granted "multinational corporations parity with sovereign governments" through the ceo roundtable and leaders\' plenary, while providing no equivalent high-level platform for civil society, labour leaders, or human rights defenders. a separate analysis contended that india\'s approach to ai governance, like france\'s before it, treated the summits primarily as trade events, and that any delhi declaration was unlikely to translate into substantive global governance commitments.[31]\n\ntechpolicy.press also reported that the united states delegation arrived at the summit with an agenda centred on "domination" rather than cooperation, framing ai as a geopolitical race against china.[32]\n\noutlook india published an analysis of the summit\'s engagement with ai risks, including environmental impact, labour displacement, and the potential for surveillance and bias.[33]\n\nsummit series [ edit ]\n\nsee also [ edit ] my six can be your nine.\n\nas professor neha of galgotias university defended the indefensible, social media did what it does best: loop, remix, ridicule.\n\nwithin hours the clip was everywhere. by the end of it, i felt oddly sympathetic – for the professor, for her students, even for the dd news reporter whose breezy “news” package turned into global meme material. it cannot be pleasant to find yourself at the centre of an internet pile-on.\n\ni have to admit i quite enjoyed the memes too, but here’s the problem. we are very good at enjoying the spectacle of humiliation. we are less good at locating responsibility.\n\nthe problem is not one professor improvising innovation and then fumbling her way through her defence. the problem is a political culture that, over the past 12 years, has turned sycophancy into policy. deference to power is not new in india. what is mind boggling now is the very formal reward structure. an indian express report said that the university bagged a booth bigger than what four iits got combined. for what reason could that be other than aligning itself with the current government’s vision of higher education? the whole mess began with someone at dd news deciding galgotias was worth amplifying. i refuse to believe that was the reporter’s call. nonetheless, we see him move from one “innovation” to another, prompting gently: you built this?\n\n“yes. end-to-end engineering.”\n\nyou built this 3d printer?\n\nthis time not neha, but a student who responded honestly: ‘actually the 3d printer had been provided by the university, among other things.’\n\nthat was the red flag. a teacher claiming total credit. a hesitant student qualifying it. any editor with minimal scepticism would have paused. are we reporting? or airing a brochure?\n\nbut the segment aired. the memes followed.\n\nif editors at dd news, if they exist, had applied even basic scrutiny, this would have remained a campus demo. instead, journalism, now indistinguishable from pr, made a silly exaggeration combustible. when your primetime model includes figures like sudhir chaudhary, this outcome is not surprising.\n\nthe culture that produces six is nine\n\nfor over a decade now, the message from the top has been unmistakable: loyalty is currency. those who chant the right slogans, who perform allegiance loudly enough, who say “modi ji zindabad” at the correct decibel – they rise. those who question are suspect.\n\nwe’ve seen what this did to television news. between 7 and 9 pm, most channels are unwatchable. credibility has collapsed so completely that even the political class they serve must privately wonder about the return on investment.\n\nwhen sycophancy becomes a pathway to success, institutions adapt. universities are beginning to mirror the same logic. the thrust is no longer to produce students who think, question, experiment. the thrust is to produce compliance. march in formation. sing on cue.\n\nask a question, and you risk being labelled anti-national. raise doubt, and you’re slotted into some convenient “gang.” there is always someone on primetime anyway ready to malign you.\n\nsince 2022, i have been to several colleges and i have lost count of the number of times i have heard students complain: the university doesn’t want us to be thinking citizens, protest karna mana hai, campus main azadi nahin hai khul ke bolne ki, vc bilkul ek ideology ko promote kar rahe hain.\n\ni won’t get into the left vs right debates on campuses but the simple fact is that innovation cannot grow in an ecosystem that punishes questioning. before we start announcing ourselves as the next great ai powerhouse, we need to confront this basic truth.\n\nthe real win for india’s ai summit\n\nand yet, this was not the whole story of india’s first ai summit.\n\ni attended it on the third day. without the vip theatre, entry was easy. and away from the galgotias stall, there was serious work happening.\n\nno, we are not outpacing china. we are not dethroning the united states. but indian companies are building systems designed for indian constraints. that was heartening to see.\n\nglobally, much of the ai conversation is capability-driven: what can ai generate? how realistic? how fast? text, video, avatars, copilots, autonomous agents. but capability is not the same as problem definition.\n\nthe viral brad pitt-tom cruise ai fight video demonstrated technical sophistication. but what human constraint did it remove? what systemic bottleneck did it address?\n\nat the ai summit, i found that much of the more interesting ai work is seriously thinking about this.\n\nthere was plenome, wadhwani ai, ai4bharat, iit madras, gnani.ai, and a bunch of other companies and organisations thinking of everyday fixes. can we make the life of a farmer, an asha worker or someone sitting somewhere in rural telangana easier with ai? can it work for someone sitting in small-town bihar with patchy internet? can it include people who don’t speak english? how can we help find solutions to our longstanding problems of educational assessments, malnutrition, digital inclusivity? i met two brothers – one had travelled from latur, another from bhopal. they were excited. there was a real twinkle in their eyes. an ambition to be part of this new technology, not left behind by it. that, to me, was the real win of the summit. a free event that allowed young people to imagine themselves inside the future.\n\nmuch of my twitter timeline is geeking out over sarvam – is it really that big a deal? oh yes it is. but google ai did the same thing? but we’re doing it better. i don’t care much for this mostly because it’s all jargon i don’t get. what interests me is this: can indian companies build for indians? in indian languages? for indian realities? can we bring non-english speakers into the ai conversation? can we serve our own market, in our own languages, with our own companies? that i think deserves more attention rather than a simplistic ask of our own ‘deepseek moment’. the conversations i had were about taking small wins, knowing that ai won’t fix everything but it can improve lives. how can we help humans rather than replace them?\n\nthe central question was not whether ai can generate astonishing videos. it clearly can.\n\nthe question is: who defines the problem ai is meant to solve? if the problem is engagement and views, we will get more synthetic spectacle.\n\nif the problem is institutional bottlenecks – overloaded doctors, under-resourced teachers, language barriers in governance – we will get quieter tools that rarely trend on social media.\n\nthe galgotias episode reveals what happens when performance culture overtakes substance. the summit’s smaller deployments tell us about another possibility: that “small” systems, designed for real constraints, can produce large impacts.\n\nthe danger is not that india may stay behind in ai capability. it is that we might prioritise applause over accuracy. if we reward spectacle, we will manufacture more “six is nine” moments.\n\nif we reward problem-solving, a culture of admitting to ourselves that a problem exists in the first place, we might actually outpace the world. in our very own way.\n\nfrom manikarnika ghat to the kashi vishwanath corridor, banaras is being reshaped in the name of vikas. our new nl sena asks who pays the price. power it here . galgotias university, which is facing an online uproar over claims that the institution had developed and showcased a chinese-made robotic dog as its own at the india ai impact summit in delhi, has clarified it never claimed to have built the device. the greater noida-based university said the robodog on display was procured from unitree, a chinese robotics firm, and was being used as a learning tool for students.\n\nadvertisement\n\nfollowing the controversy, galgotias university was asked to exit the ai summit immediately, government sources said. however, the institution said it did not receive any such order from the government.\n\nthe clarification followed a wave of social media backlash after a viral video surfaced claiming that a university professor, neha singh, had showcased the unitree go2 — an ai-powered chinese robodog sold online for usd 2,800 (around rs 2.3 lakh) — under the name “orion” at the summit. several users accused the institution of passing off imported technology as an indigenously developed product.\n\nthis has been developed by the centre of excellence at galgotiyas university.\n\n\n\n“also we are the first private university that has invested around 350 crores in artificial intelligence”. https://t.co/njfdzl7lg2 pic.twitter.com/tmqfsb6k0v february 17, 2026\n\n“the recently acquired robodog from unitree is one such step in that journey. it is not merely a machine on display; it is a classroom in motion. our students are experimenting with it, testing its limits and, in the process, expanding their own knowledge. let us be clear: galgotias has not built this robodog, nor have we ever claimed to,” the university said in a statement posted on x.\n\nthe university faced further embarrassment when its clarification was fact-checked by an x community note, which said that its claim of not presenting the robodog as its own was incorrect and misleading. “they have named the robot ‘orion’ and explicitly claimed it was developed by their team,” the note said.\n\nin the statement, the university said innovation and learning should not be confined by borders and that it would continue to source the best technologies from around the world to give students hands-on exposure.\n\nthe controversy was triggered by the viral video in which neha singh, galgotias\' professor, claimed that the university\'s centre of excellence had developed “orion” under the institution\'s rs 350 crore ai initiative. in the video, singh was proudly explaining the features of the chinese-made robodog at the ai summit, triggering a huge controversy.\n\nadvertisement\n\nresponding to the criticism, galgotias said its mission was to keep students ahead of the technology curve. it said it had consistently brought cutting-edge technologies to its campus from global innovation hubs, including the us, china and singapore, to ensure students gain real-world exposure.\n\n“innovation knows no borders. learning should not either,” the university said, adding that its focus was on enabling students to study advanced technologies, question them and improve upon them.\n\nthe institution said the initiative was not about importing technology but about inspiring transformation, underlining that its larger goal was to empower young innovators to think bigger and build world-class solutions from india for the world.\n\n- ends new delhi | the internet never forgets and the dog-eat-dog world of social media probably won\'t let you pass off a chinese product as a greater noida innovation, private university galgotias found out the hard way on being forced out of the ai impact summit on wednesday.\n\nuniversity representatives showcased a robotic dog named orion on tuesday, claiming it was developed by the centre of excellence at galgotias, prompting social media users to highlight that it was a unitree go2, manufactured by china’s unitree robotics and commonly used in research and education worldwide.\n\nbitten but not shy, the private university made a dogged attempt to brazen it out with bizarre justifications through wednesday, such as one person\'s six could be another\'s nine, but issued 

In [30]:
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp(all_text)
sentences = pd.DataFrame([sent.text for sent in doc.sents])
sentences

                                                     0
0    2026 conference in delhi, india\n\nthe ai impa...
1    the summit was inaugurated by prime minister n...
2    the opening ceremony was also addressed by fre...
3    background [ edit ]\n\nthe ai impact summit is...
4    it follows the ai action summit in paris in fe...
..                                                 ...
508  “we at galgotias university, wish to apologise...
509  one of our representatives, manning the pavili...
510  she was not aware of the technical origins of ...
511                       the wire is now on whatsapp.
512  follow our channel for sharp analysis and opin...

[513 rows x 1 columns]

Comparision of tokenized sentences with a claim to check validity (sample output)

In [32]:
claim = nlp("the galgotias university made an ai powered robot dog in their centre of excellence")
matches = sentences[0].apply(lambda x: nlp(x).similarity(claim))
matches

C:\Users\faman\AppData\Local\Temp\ipykernel_9312\1433784479.py:2: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  matches = sentences[0].apply(lambda x: nlp(x).similarity(claim))

0      0.672527
1      0.527605
2      0.694196
3      0.487935
4      0.524256
         ...
508    0.454190
509    0.204226
510    0.532905
511    0.247478
512    0.367081
Name: 0, Length: 513, dtype: float64

In [44]:
#tried to find the most similar sentences to the claim but they do not seem relevant when viewd manually. This could be because the claim is very specific and the sentences in the collected data may not have enough context to match it accurately. The similarity score is based on the overall meaning of the sentences, so it may not capture specific details that are crucial for verifying the claim.
matches.sort_values(ascending=False)
indices=matches.sort_values(ascending=False).head(15).index
print(indices)
print(sentences.iloc[indices])

Index([202, 428, 464, 260, 478, 466, 249, 2, 140, 12, 0, 254, 382, 15, 430], dtype='int64')
                                                     0
202  show quick read key points generated by ai, ve...
428  a commercial product of unitree go2, this chin...
464  the galgotias university incident has put the ...
260  galgotias university proudly ascends in the qs...
478  the controversy erupted on wednesday when a pr...
466  galgotias university, a private institution, h...
249  galgotias university pavilion at ai impact sum...
2    the opening ceremony was also addressed by fre...
140  - ends new delhi | the internet never forgets ...
12   social media users identified the robot as the...
0    2026 conference in delhi, india\n\nthe ai impa...
254  the stall also highlighted ai-driven centres o...
382  india's galgotias university courted a major c...
15   only to see our wearables disappear inside a h...
430  galgotias university turns a robodog into nati...

In [50]:
if(matches.mean()>0.75):
    print("The claim is likely to be true based on the collected data.")
else:
    print("The claim is likely to be false based on the collected data.")

The claim is likely to be false based on the collected data.